# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\"$\n\x10InitOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"+\n\x11InitOrderResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\n\n\x02vc\x18\x02 \x03(\x05\"Y\n\x12SuggestionsRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x17\n\x0fpurchased_books\x18\x02 \x03(\t\x12\x0c\n\x04mode\x18\x03 \x01(\t\x12\n\n\x02vc\x18\x04 \x03(\x05\":\n\x13SuggestionsResponse\x12\x17\n\x0fsuggested_books\x18\x01 \x03(\t\x12\n\n\x02vc\x18\x02 \x03(\x05\"4\n\x14\x46inalizeOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\n\n\x02vc\x18\x02 \x03(\x05\"/\n\x15\x46inalizeOrderResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\n\n\x02vc\x18\x02 \x03(\x05\x32\x8d\x02\n\x12SuggestionsService\x12J\n\tInitOrder\x12\x1d.suggestions.InitOrderRequest\x1a\x1e.suggestions.InitOrderResponse\x12S\n\x0eGetSuggestions\x12\x1f.suggestions.SuggestionsRequest\x1a .suggestions.SuggestionsResponse\x12V\n\rFinalizeOrder\x12!.suggestions.FinalizeOrderRequest\x1a\".suggestions.FinalizeOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITORDERREQUEST']._serialized_start=34
  _globals['_INITORDERREQUEST']._serialized_end=70
  _globals['_INITORDERRESPONSE']._serialized_start=72
  _globals['_INITORDERRESPONSE']._serialized_end=115
  _globals['_SUGGESTIONSREQUEST']._serialized_start=117
  _globals['_SUGGESTIONSREQUEST']._serialized_end=206
  _globals['_SUGGESTIONSRESPONSE']._serialized_start=208
  _globals['_SUGGESTIONSRESPONSE']._serialized_end=266
  _globals['_FINALIZEORDERREQUEST']._serialized_start=268
  _globals['_FINALIZEORDERREQUEST']._serialized_end=320
  _globals['_FINALIZEORDERRESPONSE']._serialized_start=322
  _globals['_FINALIZEORDERRESPONSE']._serialized_end=369
  _globals['_SUGGESTIONSSERVICE']._serialized_start=372
  _globals['_SUGGESTIONSSERVICE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
