# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books_database.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'books_database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ooks_database.proto\"\x07\n\x05\x45mpty\"\'\n\x16\x41vailableBooksResponse\x12\r\n\x05\x62ooks\x18\x01 \x03(\t\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\"0\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\"3\n\x10\x44\x65\x63rementRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc8\x01\n\rBooksDatabase\x12#\n\x04Read\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12&\n\x05Write\x12\r.WriteRequest\x1a\x0e.WriteResponse\x12\x33\n\x0e\x44\x65\x63rementStock\x12\x11.DecrementRequest\x1a\x0e.WriteResponse\x12\x35\n\x12ListAvailableBooks\x12\x06.Empty\x1a\x17.AvailableBooksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=24
  _globals['_EMPTY']._serialized_end=31
  _globals['_AVAILABLEBOOKSRESPONSE']._serialized_start=33
  _globals['_AVAILABLEBOOKSRESPONSE']._serialized_end=72
  _globals['_READREQUEST']._serialized_start=74
  _globals['_READREQUEST']._serialized_end=102
  _globals['_READRESPONSE']._serialized_start=104
  _globals['_READRESPONSE']._serialized_end=133
  _globals['_WRITEREQUEST']._serialized_start=135
  _globals['_WRITEREQUEST']._serialized_end=183
  _globals['_DECREMENTREQUEST']._serialized_start=185
  _globals['_DECREMENTREQUEST']._serialized_end=236
  _globals['_WRITERESPONSE']._serialized_start=238
  _globals['_WRITERESPONSE']._serialized_end=270
  _globals['_BOOKSDATABASE']._serialized_start=273
  _globals['_BOOKSDATABASE']._serialized_end=473
# @@protoc_insertion_point(module_scope)
