# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/order_queue/order_queue.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'utils/pb/order_queue/order_queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/order_queue/order_queue.proto\x12\x0border_queue\"+\n\tOrderItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\xdb\x02\n\x0e\x45nqueueRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x16\n\x0epurchaser_name\x18\x02 \x01(\t\x12\x17\n\x0fpurchaser_email\x18\x03 \x01(\t\x12\x1a\n\x12\x63redit_card_number\x18\x04 \x01(\t\x12\x1e\n\x16\x63redit_card_expiration\x18\x05 \x01(\t\x12\x17\n\x0f\x63redit_card_cvv\x18\x06 \x01(\t\x12\x16\n\x0e\x62illing_street\x18\x07 \x01(\t\x12\x14\n\x0c\x62illing_city\x18\x08 \x01(\t\x12\x15\n\rbilling_state\x18\t \x01(\t\x12\x13\n\x0b\x62illing_zip\x18\n \x01(\t\x12\x17\n\x0f\x62illing_country\x18\x0b \x01(\t\x12%\n\x05items\x18\x0c \x03(\x0b\x32\x16.order_queue.OrderItem\x12\x17\n\x0fsuggested_books\x18\r \x03(\t\"\x1d\n\x0f\x45nqueueResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x10\n\x0e\x44\x65queueRequest\"\xe8\x02\n\x0f\x44\x65queueResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x16\n\x0epurchaser_name\x18\x03 \x01(\t\x12\x17\n\x0fpurchaser_email\x18\x04 \x01(\t\x12\x1a\n\x12\x63redit_card_number\x18\x05 \x01(\t\x12\x1e\n\x16\x63redit_card_expiration\x18\x06 \x01(\t\x12\x17\n\x0f\x63redit_card_cvv\x18\x07 \x01(\t\x12\x16\n\x0e\x62illing_street\x18\x08 \x01(\t\x12\x14\n\x0c\x62illing_city\x18\t \x01(\t\x12\x15\n\rbilling_state\x18\n \x01(\t\x12\x13\n\x0b\x62illing_zip\x18\x0b \x01(\t\x12\x17\n\x0f\x62illing_country\x18\x0c \x01(\t\x12%\n\x05items\x18\r \x03(\x0b\x32\x16.order_queue.OrderItem\x12\x17\n\x0fsuggested_books\x18\x0e \x03(\t2\x9f\x01\n\x11OrderQueueService\x12\x44\n\x07\x45nqueue\x12\x1b.order_queue.EnqueueRequest\x1a\x1c.order_queue.EnqueueResponse\x12\x44\n\x07\x44\x65queue\x12\x1b.order_queue.DequeueRequest\x1a\x1c.order_queue.DequeueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_queue.order_queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERITEM']._serialized_start=55
  _globals['_ORDERITEM']._serialized_end=98
  _globals['_ENQUEUEREQUEST']._serialized_start=101
  _globals['_ENQUEUEREQUEST']._serialized_end=448
  _globals['_ENQUEUERESPONSE']._serialized_start=450
  _globals['_ENQUEUERESPONSE']._serialized_end=479
  _globals['_DEQUEUEREQUEST']._serialized_start=481
  _globals['_DEQUEUEREQUEST']._serialized_end=497
  _globals['_DEQUEUERESPONSE']._serialized_start=500
  _globals['_DEQUEUERESPONSE']._serialized_end=860
  _globals['_ORDERQUEUESERVICE']._serialized_start=863
  _globals['_ORDERQUEUESERVICE']._serialized_end=1022
# @@protoc_insertion_point(module_scope)
