# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import transaction_verification_pb2 as transaction__verification__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in transaction_verification_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransactionVerificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/InitOrder',
                request_serializer=transaction__verification__pb2.InitOrderRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.InitOrderResponse.FromString,
                _registered_method=True)
        self.CheckItems = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/CheckItems',
                request_serializer=transaction__verification__pb2.TransactionEventRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.TransactionEventResponse.FromString,
                _registered_method=True)
        self.CheckUserAndBillingData = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/CheckUserAndBillingData',
                request_serializer=transaction__verification__pb2.TransactionEventRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.TransactionEventResponse.FromString,
                _registered_method=True)
        self.CheckPaymentData = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/CheckPaymentData',
                request_serializer=transaction__verification__pb2.TransactionEventRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.TransactionEventResponse.FromString,
                _registered_method=True)
        self.FinalizeOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/FinalizeOrder',
                request_serializer=transaction__verification__pb2.FinalizeOrderRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.FinalizeOrderResponse.FromString,
                _registered_method=True)
        self.StartWorkflow = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/StartWorkflow',
                request_serializer=transaction__verification__pb2.StartWorkflowRequest.SerializeToString,
                response_deserializer=transaction__verification__pb2.WorkflowResponse.FromString,
                _registered_method=True)


class TransactionVerificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserAndBillingData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPaymentData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionVerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitOrder,
                    request_deserializer=transaction__verification__pb2.InitOrderRequest.FromString,
                    response_serializer=transaction__verification__pb2.InitOrderResponse.SerializeToString,
            ),
            'CheckItems': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckItems,
                    request_deserializer=transaction__verification__pb2.TransactionEventRequest.FromString,
                    response_serializer=transaction__verification__pb2.TransactionEventResponse.SerializeToString,
            ),
            'CheckUserAndBillingData': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserAndBillingData,
                    request_deserializer=transaction__verification__pb2.TransactionEventRequest.FromString,
                    response_serializer=transaction__verification__pb2.TransactionEventResponse.SerializeToString,
            ),
            'CheckPaymentData': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPaymentData,
                    request_deserializer=transaction__verification__pb2.TransactionEventRequest.FromString,
                    response_serializer=transaction__verification__pb2.TransactionEventResponse.SerializeToString,
            ),
            'FinalizeOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeOrder,
                    request_deserializer=transaction__verification__pb2.FinalizeOrderRequest.FromString,
                    response_serializer=transaction__verification__pb2.FinalizeOrderResponse.SerializeToString,
            ),
            'StartWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.StartWorkflow,
                    request_deserializer=transaction__verification__pb2.StartWorkflowRequest.FromString,
                    response_serializer=transaction__verification__pb2.WorkflowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction_verification.TransactionVerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transaction_verification.TransactionVerificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionVerificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerificationService/InitOrder',
            transaction__verification__pb2.InitOrderRequest.SerializeToString,
            transaction__verification__pb2.InitOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerificationService/CheckItems',
            transaction__verification__pb2.TransactionEventRequest.SerializeToString,
            transaction__verification__pb2.TransactionEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUserAndBillingData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerificationService/CheckUserAndBillingData',
            transaction__verification__pb2.TransactionEventRequest.SerializeToString,
            transaction__verification__pb2.TransactionEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPaymentData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerificationService/CheckPaymentData',
            transaction__verification__pb2.TransactionEventRequest.SerializeToString,
            transaction__verification__pb2.TransactionEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerificationService/FinalizeOrder',
            transaction__verification__pb2.FinalizeOrderRequest.SerializeToString,
            transaction__verification__pb2.FinalizeOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerificationService/StartWorkflow',
            transaction__verification__pb2.StartWorkflowRequest.SerializeToString,
            transaction__verification__pb2.WorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
