# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/payment/payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'utils/pb/payment/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eutils/pb/payment/payment.proto\"~\n\x15PaymentPrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x1a\n\x12\x63redit_card_number\x18\x02 \x01(\t\x12\x1e\n\x16\x63redit_card_expiration\x18\x03 \x01(\t\x12\x17\n\x0f\x63redit_card_cvv\x18\x04 \x01(\t\"\'\n\x16PaymentPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"(\n\x14PaymentCommitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"(\n\x15PaymentCommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\'\n\x13PaymentAbortRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\'\n\x14PaymentAbortResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x32\xbb\x01\n\x0ePaymentService\x12:\n\x07Prepare\x12\x16.PaymentPrepareRequest\x1a\x17.PaymentPrepareResponse\x12\x37\n\x06\x43ommit\x12\x15.PaymentCommitRequest\x1a\x16.PaymentCommitResponse\x12\x34\n\x05\x41\x62ort\x12\x14.PaymentAbortRequest\x1a\x15.PaymentAbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.payment.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTPREPAREREQUEST']._serialized_start=34
  _globals['_PAYMENTPREPAREREQUEST']._serialized_end=160
  _globals['_PAYMENTPREPARERESPONSE']._serialized_start=162
  _globals['_PAYMENTPREPARERESPONSE']._serialized_end=201
  _globals['_PAYMENTCOMMITREQUEST']._serialized_start=203
  _globals['_PAYMENTCOMMITREQUEST']._serialized_end=243
  _globals['_PAYMENTCOMMITRESPONSE']._serialized_start=245
  _globals['_PAYMENTCOMMITRESPONSE']._serialized_end=285
  _globals['_PAYMENTABORTREQUEST']._serialized_start=287
  _globals['_PAYMENTABORTREQUEST']._serialized_end=326
  _globals['_PAYMENTABORTRESPONSE']._serialized_start=328
  _globals['_PAYMENTABORTRESPONSE']._serialized_end=367
  _globals['_PAYMENTSERVICE']._serialized_start=370
  _globals['_PAYMENTSERVICE']._serialized_end=557
# @@protoc_insertion_point(module_scope)
