# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from utils.pb.payment import payment_pb2 as utils_dot_pb_dot_payment_dot_payment__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in utils/pb/payment/payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prepare = channel.unary_unary(
                '/PaymentService/Prepare',
                request_serializer=utils_dot_pb_dot_payment_dot_payment__pb2.PaymentPrepareRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_payment_dot_payment__pb2.PaymentPrepareResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/PaymentService/Commit',
                request_serializer=utils_dot_pb_dot_payment_dot_payment__pb2.PaymentCommitRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_payment_dot_payment__pb2.PaymentCommitResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/PaymentService/Abort',
                request_serializer=utils_dot_pb_dot_payment_dot_payment__pb2.PaymentAbortRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_payment_dot_payment__pb2.PaymentAbortResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=utils_dot_pb_dot_payment_dot_payment__pb2.PaymentPrepareRequest.FromString,
                    response_serializer=utils_dot_pb_dot_payment_dot_payment__pb2.PaymentPrepareResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=utils_dot_pb_dot_payment_dot_payment__pb2.PaymentCommitRequest.FromString,
                    response_serializer=utils_dot_pb_dot_payment_dot_payment__pb2.PaymentCommitResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=utils_dot_pb_dot_payment_dot_payment__pb2.PaymentAbortRequest.FromString,
                    response_serializer=utils_dot_pb_dot_payment_dot_payment__pb2.PaymentAbortResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/Prepare',
            utils_dot_pb_dot_payment_dot_payment__pb2.PaymentPrepareRequest.SerializeToString,
            utils_dot_pb_dot_payment_dot_payment__pb2.PaymentPrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/Commit',
            utils_dot_pb_dot_payment_dot_payment__pb2.PaymentCommitRequest.SerializeToString,
            utils_dot_pb_dot_payment_dot_payment__pb2.PaymentCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PaymentService/Abort',
            utils_dot_pb_dot_payment_dot_payment__pb2.PaymentAbortRequest.SerializeToString,
            utils_dot_pb_dot_payment_dot_payment__pb2.PaymentAbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
